// Lightweight index of landing page campaigns for the homepage's "Explore
// our resources" section — deliberately separate from the full content in
// content/landing-pages/*.json (which build scripts read directly) so this
// tiny manifest is all that ships in the client bundle. Keep in sync with
// content/landing-pages/ when adding a new campaign page.
export const CAMPAIGN_CATEGORIES = [
  {
    title: 'DoD & Military Training',
    pages: [
      { slug: 'dod-cyber-awareness-challenge', label: 'DoD Cyber Awareness Challenge' },
      { slug: 'opsec-training', label: 'OPSEC Training' },
      { slug: 'information-assurance-training', label: 'Information Assurance (IA) Training' },
      { slug: 'anti-terrorism-level-1-training', label: 'Antiterrorism Level 1 Training' },
      { slug: 'combating-trafficking-in-persons-training', label: 'Combating Trafficking in Persons (CTIP)' },
      { slug: 'cui-training', label: 'CUI Training' },
      { slug: 'pii-training', label: 'PII Training' },
      { slug: 'insider-threat-awareness-training', label: 'Insider Threat Awareness Training' },
      { slug: 'tarp-training', label: 'TARP Training' },
      { slug: 'law-of-war-training', label: 'Law of War Training' },
      { slug: 'sere-100-2-training', label: 'SERE 100.2 Training' },
      { slug: 'dod-annual-security-awareness-refresher-training', label: 'DoD Annual Security Awareness Refresher' },
      { slug: 'derivative-classification-training', label: 'Derivative Classification Training' },
      { slug: 'sapr-training', label: 'SAPR Training' },
      { slug: 'suicide-prevention-training', label: 'Suicide Prevention (ACE) Training' },
      { slug: 'marking-classified-information-training', label: 'Marking Classified Information Training' },
      { slug: 'anti-terrorism-level-2-training', label: 'Antiterrorism Level II Training' },
      { slug: 'counterintelligence-awareness-training', label: 'Counterintelligence Awareness Training' },
      { slug: 'privileged-user-cybersecurity-training', label: 'Privileged User Cybersecurity Responsibilities' },
    ],
  },
  {
    title: 'Workplace Compliance',
    pages: [
      { slug: 'hipaa-training', label: 'HIPAA Training' },
      { slug: 'sexual-harassment-prevention-training', label: 'Sexual Harassment Prevention Training' },
      { slug: 'active-shooter-training', label: 'Active Shooter Training' },
      { slug: 'osha-10-hour-training', label: 'OSHA 10-Hour Training' },
      { slug: 'anti-money-laundering-training', label: 'Anti-Money Laundering (AML) Training' },
      { slug: 'bloodborne-pathogens-training', label: 'Bloodborne Pathogens Training' },
      { slug: 'osha-30-hour-training', label: 'OSHA 30-Hour Training' },
      { slug: 'forklift-certification-training', label: 'Forklift Certification Training' },
      { slug: 'food-handler-card-practice-test', label: 'Food Handler Card Practice Test' },
      { slug: 'servsafe-manager-exam-practice', label: 'ServSafe Manager Exam Practice' },
      { slug: 'hazwoper-40-hour-training', label: 'HAZWOPER 40-Hour Training' },
      { slug: 'california-mandated-reporter-training', label: 'California Mandated Reporter Training' },
    ],
  },
  {
    title: 'Career & Aptitude Tests',
    pages: [
      { slug: 'ccat-practice-test', label: 'CCAT Practice Test' },
      { slug: 'wonderlic-test-practice', label: 'Wonderlic Test Practice' },
      { slug: 'predictive-index-cognitive-assessment', label: 'Predictive Index Cognitive Assessment' },
      { slug: 'shl-test-practice', label: 'SHL Test Practice' },
      { slug: 'caliper-assessment-practice', label: 'Caliper Assessment Practice' },
      { slug: 'hogan-assessment-practice', label: 'Hogan Assessment Practice' },
      { slug: 'asvab-practice-test', label: 'ASVAB Practice Test' },
      { slug: 'pmp-exam-practice', label: 'PMP Exam Practice' },
    ],
  },
  {
    title: 'Professional Certifications',
    pages: [
      { slug: 'comptia-security-plus-practice-test', label: 'CompTIA Security+ Practice Test' },
      { slug: 'comptia-a-plus-practice-test', label: 'CompTIA A+ Practice Test' },
      { slug: 'aws-cloud-practitioner-practice-test', label: 'AWS Cloud Practitioner Practice Test' },
      { slug: 'nclex-rn-practice-questions', label: 'NCLEX-RN Practice Questions' },
      { slug: 'teas-7-practice-test', label: 'TEAS 7 Practice Test' },
      { slug: 'sie-exam-practice', label: 'SIE Exam Practice' },
      { slug: 'ptce-practice-test', label: 'PTCE (Pharmacy Tech) Practice Test' },
      { slug: 'epa-608-practice-test', label: 'EPA 608 Practice Test' },
    ],
  },
  {
    title: 'State Licensing & Exams',
    pages: [
      { slug: 'texas-real-estate-exam-prep', label: 'Texas Real Estate Exam Prep' },
      { slug: 'california-real-estate-exam-prep', label: 'California Real Estate Exam Prep' },
      { slug: 'florida-real-estate-exam-prep', label: 'Florida Real Estate Exam Prep' },
      { slug: 'life-and-health-insurance-license-exam-prep', label: 'Life & Health Insurance License Exam Prep' },
      { slug: 'cdl-general-knowledge-practice-test', label: 'CDL General Knowledge Practice Test' },
      { slug: 'texas-food-handler-card-practice-test', label: 'Texas Food Handler Card Practice Test' },
      { slug: 'california-food-handler-card-practice-test', label: 'California Food Handler Card Practice Test' },
    ],
  },
  {
    title: 'Course & Campus Study Tools',
    pages: [
      { slug: 'intro-psychology-practice-quiz', label: 'Intro Psychology Practice Quiz' },
      { slug: 'microeconomics-practice-quiz', label: 'Microeconomics Practice Quiz' },
      { slug: 'macroeconomics-practice-quiz', label: 'Macroeconomics Practice Quiz' },
      { slug: 'financial-accounting-practice-quiz', label: 'Financial Accounting Practice Quiz' },
      { slug: 'intro-biology-practice-quiz', label: 'Intro Biology Practice Quiz' },
      { slug: 'general-chemistry-practice-quiz', label: 'General Chemistry Practice Quiz' },
      { slug: 'college-algebra-practice-quiz', label: 'College Algebra Practice Quiz' },
      { slug: 'intro-statistics-practice-quiz', label: 'Intro Statistics Practice Quiz' },
      { slug: 'intro-sociology-practice-quiz', label: 'Intro Sociology Practice Quiz' },
      { slug: 'us-history-survey-1-practice-quiz', label: 'U.S. History Survey I Practice Quiz' },
      { slug: 'us-history-survey-2-practice-quiz', label: 'U.S. History Survey II Practice Quiz' },
      { slug: 'intro-to-business-practice-quiz', label: 'Intro to Business Practice Quiz' },
      { slug: 'anatomy-physiology-practice-quiz', label: 'Anatomy & Physiology Practice Quiz' },
      { slug: 'nutrition-practice-quiz', label: 'Nutrition Practice Quiz' },
      { slug: 'environmental-science-practice-quiz', label: 'Environmental Science Practice Quiz' },
      { slug: 'astronomy-101-practice-quiz', label: 'Astronomy 101 Practice Quiz' },
      { slug: 'marketing-principles-practice-quiz', label: 'Marketing Principles Practice Quiz' },
      { slug: 'management-principles-practice-quiz', label: 'Management Principles Practice Quiz' },
      { slug: 'intro-finance-practice-quiz', label: 'Intro Finance Practice Quiz' },
      { slug: 'music-appreciation-practice-quiz', label: 'Music Appreciation Practice Quiz' },
      { slug: 'art-appreciation-practice-quiz', label: 'Art Appreciation Practice Quiz' },
      { slug: 'american-government-practice-quiz', label: 'American Government Practice Quiz' },
      { slug: 'mcgraw-hill-connect-answers', label: 'McGraw Hill Connect' },
      { slug: 'pearson-mylab-answers', label: 'Pearson MyLab' },
      { slug: 'cengage-mindtap-answers', label: 'Cengage MindTap' },
      { slug: 'aplia-answers', label: 'Aplia' },
      { slug: 'tophat-answers', label: 'Top Hat' },
    ],
  },
];

// School hub pages aren't quizzes (no sampleQuestions), so they're kept out
// of CAMPAIGN_CATEGORIES (the "example quizzes" chip index) — they're
// discovered via their own course-page cross-links instead, computed at
// build time from content/course-catalog.json.
export const SCHOOL_HUBS = [
  { slug: 'university-of-alabama-study-tools', label: 'University of Alabama' },
  { slug: 'ole-miss-study-tools', label: 'Ole Miss' },
  { slug: 'lsu-study-tools', label: 'LSU' },
  { slug: 'university-of-georgia-study-tools', label: 'University of Georgia' },
  { slug: 'auburn-study-tools', label: 'Auburn University' },
  { slug: 'tulane-study-tools', label: 'Tulane University' },
  { slug: 'miami-oh-study-tools', label: 'Miami University (Ohio)' },
  { slug: 'smu-study-tools', label: 'SMU' },
  { slug: 'university-of-miami-study-tools', label: 'University of Miami' },
  { slug: 'tcu-study-tools', label: 'TCU' },
  { slug: 'indiana-study-tools', label: 'Indiana University Bloomington' },
  { slug: 'wisconsin-study-tools', label: 'University of Wisconsin-Madison' },
  { slug: 'michigan-study-tools', label: 'University of Michigan' },
  { slug: 'asu-study-tools', label: 'Arizona State University' },
  { slug: 'ut-austin-study-tools', label: 'University of Texas at Austin' },
  { slug: 'florida-study-tools', label: 'University of Florida' },
  { slug: 'penn-state-study-tools', label: 'Penn State University' },
  { slug: 'syracuse-study-tools', label: 'Syracuse University' },
];
