import { Link } from 'react-router-dom';
import { useAuthContext } from '../lib/AuthContext.jsx';
import Sidebar from '../components/Sidebar.jsx';
import Seo from '../components/Seo.jsx';
import ResourcesFooter from '../components/ResourcesFooter.jsx';

const NAV_ITEMS = [
  { label: 'How it works', href: '/#how' },
  { label: 'Why tutors', href: '/#why' },
  { label: 'Pricing', href: '/pricing' },
  { label: 'FAQ', href: '/#faq' },
];

const LAST_UPDATED = 'August 29, 2026';

function TermsOfService() {
  const { user } = useAuthContext();

  return (
    <div className="landing">
      <Seo
        title="Terms of Service — Cambo App"
        description="The terms that apply when you use Cambo."
        path="/terms"
      />
      <Sidebar navItems={NAV_ITEMS} user={user} />

      <div className="mkt-main">
        <section className="pricing-page legal-page">
          <div className="pricing-page-head">
            <div className="section-eyebrow">Terms of Service</div>
            <h1>Terms of Service</h1>
            <p>Last updated: {LAST_UPDATED}</p>
          </div>

          <div className="legal-content">
            <p>
              These terms govern your use of Cambo (camboapp.com and the Cambo app). By
              creating an account or using Cambo, you agree to these terms.
            </p>

            <h2>The service</h2>
            <p>
              Cambo lets you photograph a practice question and receive an
              AI-generated answer. Answers are generated automatically and are provided
              to help tutors and students move through practice material — they are not
              guaranteed to be correct, and should be checked before being relied on,
              especially for graded or high-stakes work.
            </p>

            <h2>Accounts</h2>
            <p>
              You need an account to use Cambo. You're responsible for keeping your
              login credentials secure and for the activity that happens under your
              account. You must provide accurate information when you register.
            </p>

            <h2>Acceptable use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Use Cambo to violate an exam's, school's, or employer's academic or testing integrity policy;</li>
              <li>Attempt to disrupt, reverse engineer, or gain unauthorized access to Cambo or its systems;</li>
              <li>Use Cambo to upload content you don't have the right to capture or share;</li>
              <li>Resell or redistribute access to Cambo without our permission.</li>
            </ul>
            <p>
              Cambo is a study and tutoring aid. It's your responsibility to use it in a
              way that's consistent with the rules of whatever test, course, or
              certification you're studying for.
            </p>

            <h2>Plans and billing</h2>
            <p>
              Cambo offers a free tier and paid subscription plans. Paid plans are billed
              in advance through Stripe and renew automatically until cancelled. You can
              cancel at any time from your Account page; cancellation takes effect at the
              end of the current billing period. Fees are non-refundable except where
              required by law.
            </p>

            <h2>Termination</h2>
            <p>
              You may stop using Cambo and close your account at any time. We may
              suspend or terminate accounts that violate these terms or that we
              reasonably believe are being used for abuse of the service.
            </p>

            <h2>Disclaimers</h2>
            <p>
              Cambo is provided "as is." Answers are generated by automated systems and
              may contain errors. We do not guarantee that the service will be
              uninterrupted, error-free, or that any particular answer will be accurate.
            </p>

            <h2>Limitation of liability</h2>
            <p>
              To the extent permitted by law, Cambo and its operators are not liable for
              indirect, incidental, or consequential damages arising from your use of the
              service, including reliance on an answer Cambo provides.
            </p>

            <h2>Changes to these terms</h2>
            <p>
              We may update these terms from time to time. We'll update the "Last
              updated" date above when we do. Continued use of Cambo after a change means
              you accept the updated terms.
            </p>

            <h2>Contact us</h2>
            <p>
              Questions about these terms? Reach us using the "Ask a question" form on
              our home page.
            </p>
          </div>
        </section>

        <ResourcesFooter />

        <div className="footer-bottom pricing-footer-bottom">
          <div>© 2026 Cambo App</div>
          <div className="footer-links">
            <Link to="/">Home</Link>
            <Link to="/privacy">Privacy Policy</Link>
            <a href="/#ask">Ask a question</a>
          </div>
        </div>
      </div>
    </div>
  );
}

export default TermsOfService;
