// The landing-page slugs eligible to receive auto-published captured
// questions. Mirrors src/lib/campaignPages.js — kept as a separate backend
// constant rather than importing that frontend file, matching this repo's
// existing plans.js pattern of not crossing the client/server boundary.
export const PUBLIC_QUESTION_TOPICS = new Set([
  'dod-cyber-awareness-challenge',
  'opsec-training',
  'information-assurance-training',
  'anti-terrorism-level-1-training',
  'combating-trafficking-in-persons-training',
  'cui-training',
  'pii-training',
  'insider-threat-awareness-training',
  'tarp-training',
  'law-of-war-training',
  'sere-100-2-training',
  'hipaa-training',
  'sexual-harassment-prevention-training',
  'active-shooter-training',
  'osha-10-hour-training',
  'anti-money-laundering-training',
  'ccat-practice-test',
  'wonderlic-test-practice',
  'predictive-index-cognitive-assessment',
  'shl-test-practice',
  'caliper-assessment-practice',
  'hogan-assessment-practice',
  'asvab-practice-test',
  'pmp-exam-practice',
  'dod-annual-security-awareness-refresher-training',
  'derivative-classification-training',
  'sapr-training',
  'suicide-prevention-training',
  'marking-classified-information-training',
  'anti-terrorism-level-2-training',
  'counterintelligence-awareness-training',
  'privileged-user-cybersecurity-training',
  'bloodborne-pathogens-training',
  'osha-30-hour-training',
  'forklift-certification-training',
  'food-handler-card-practice-test',
  'servsafe-manager-exam-practice',
  'hazwoper-40-hour-training',
  'california-mandated-reporter-training',
  'comptia-security-plus-practice-test',
  'comptia-a-plus-practice-test',
  'aws-cloud-practitioner-practice-test',
  'nclex-rn-practice-questions',
  'teas-7-practice-test',
  'sie-exam-practice',
  'ptce-practice-test',
  'epa-608-practice-test',
  'texas-real-estate-exam-prep',
  'california-real-estate-exam-prep',
  'florida-real-estate-exam-prep',
  'life-and-health-insurance-license-exam-prep',
  'cdl-general-knowledge-practice-test',
  'texas-food-handler-card-practice-test',
  'california-food-handler-card-practice-test',
  'intro-psychology-practice-quiz',
  'microeconomics-practice-quiz',
  'macroeconomics-practice-quiz',
  'financial-accounting-practice-quiz',
  'intro-biology-practice-quiz',
  'general-chemistry-practice-quiz',
  'college-algebra-practice-quiz',
  'intro-statistics-practice-quiz',
  'intro-sociology-practice-quiz',
  'us-history-survey-1-practice-quiz',
  'us-history-survey-2-practice-quiz',
  'intro-to-business-practice-quiz',
  'anatomy-physiology-practice-quiz',
  'nutrition-practice-quiz',
  'environmental-science-practice-quiz',
  'astronomy-101-practice-quiz',
  'marketing-principles-practice-quiz',
  'management-principles-practice-quiz',
  'intro-finance-practice-quiz',
  'music-appreciation-practice-quiz',
  'art-appreciation-practice-quiz',
  'american-government-practice-quiz',
  'mcgraw-hill-connect-answers',
  'pearson-mylab-answers',
  'cengage-mindtap-answers',
  'aplia-answers',
  'tophat-answers',
]);

// Collapse whitespace/case/trailing punctuation so the same question typed
// or photographed slightly differently still dedupes to one row.
export function normalizeQuestionKey(question) {
  return question
    .toLowerCase()
    .trim()
    .replace(/\s+/g, ' ')
    .replace(/[?.!,;:'"]+$/g, '');
}
